name: login_scanner
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_listener: ^0.1.4
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  http: ^1.1.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
